### ISSUE TITLE
unregelmäßige Backups von ioBroker

### ISSUE THREAD

**Issue by Toysman** [simatec/ioBroker.backitup#381]
**Describe the bug**  
vom ioBroker werden unregelmäßig Backups erstellt (letztes vom 24.12.2020) obwohl tägliche Updates eingestellt ist,
die täglichen Backups des ZigBee Adapters werden zuverlässig erstellt.. 

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.8.3
 - JS-Controller version: 3.1.6
 - Node version: 14.5.0
 - Operating system: ioBroker

**Additional context**  
<img width="1701" alt="Bildschirmfoto 2021-01-03 um 20 29 25" src="https://user-images.githubusercontent.com/76917387/103487088-0757e000-4e03-11eb-8ed4-79ee0178f572.png">

<img width="1372" alt="Bildschirmfoto 2021-01-03 um 20 30 11" src="https://user-images.githubusercontent.com/76917387/103487096-1474cf00-4e03-11eb-83fe-4d22683097ea.png">

<img width="287" alt="Bildschirmfoto 2021-01-03 um 20 29 51" src="https://user-images.githubusercontent.com/76917387/103487097-19d21980-4e03-11eb-9dc2-4631c2d03a67.png">

**Comment by simatec** [comment]
Prüfe mal deinen täglichen Log. Was steht da um 2 Uhr drin? Laut deinen Screenshots sieht mir die eingestellte Zeit komisch aus. Das sieht mir aus, als ob da Leerzeichen in der Uhrzeit sind.

**Comment by Toysman** [comment]
Hi,
das "normale" Log habe ich gelöscht, da ich aktuell mit dem ZigBee Adapter
Probleme habe... aber in den Objekten
steht unter "ioBrokerLastTime" der 02.01.2021 - 2:00 Uhr"... insofern
eigentlich richtig, aber das Backup wird nicht
erstellt, im Gegensatz zu der Sicherung ZigBee Datenbank, die täglich
gesichert wird. Somit ist die Uhrzeit ist okay

Gruß
Harald


Am So., 3. Jan. 2021 um 20:46 Uhr schrieb simatec <notifications@github.com

**Comment by simatec** [comment]
Du kannst den Log der letzten Tage über den Button anschauen. Ohne Log kann ich leider nicht helfen

**Comment by Toysman** [comment]
ich reiche Dir ein Log in den nächsten Tagen nach, sobald ich selber wieder mehr Daten habe

besten Dank

________________________________
Von: simatec <notifications@github.com>
Gesendet: Sunday, January 3, 2021 9:22:31 PM
An: simatec/ioBroker.backitup <ioBroker.backitup@noreply.github.com>
Cc: Toysman <h.von.essen@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [simatec/ioBroker.backitup] unregelmäßige Backups von ioBroker (#381)


Du kannst den Log der letzten Tage über den Button anschauen. Ohne Log kann ich leider nicht helfen

**Comment by simatec** [comment]
Die archivierten Logs sind doch im iobroker im Tab Logs über den Button verfügbar. Da hast du alle Logs der letzten Tage

**Comment by Toysman** [comment]
gefunden... und eine ziemlich dämliche Frage... wie kann ich die runterladen, die archivierten Logs werden mir nur im Firefox angezeigt...

________________________________
Von: simatec <notifications@github.com>
Gesendet: Sunday, January 3, 2021 9:30:30 PM
An: simatec/ioBroker.backitup <ioBroker.backitup@noreply.github.com>
Cc: Toysman <h.von.essen@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [simatec/ioBroker.backitup] unregelmäßige Backups von ioBroker (#381)


Die archivierten Logs sind doch im iobroker im Tab Logs über den Button verfügbar. Da hast du alle Logs der letzten Tage

**Comment by simatec** [comment]
Im Tab Logs gibt es dafür oben einen Button

**Comment by georg1210** [comment]
Hi, ich habe ein ähnliches Problem mit Google Drive

Adapter version: 1.8.5
JS-Controller version: 3.1.6
Node version: 14.5.4
ioBroker läuft als Container (buanet-Image)

Ich habe um 02:00h verdächtige Rate Limit Exceeded Einträge, wenn kein Backup in Google Drive abgelegt wird (lokal werden sie erstellt):


backitup.0 | 2021-01-14 02:00:57.309 | info | (1048) [iobroker] backup was activated at 02:00 every 1 day(s)
-- | -- | -- | --
backitup.0 | 2021-01-14 02:00:57.229 | info | (1048) starting. Version 1.8.5 in /opt/iobroker/node_modules/iobroker.backitup, node: v14.15.4, js-controller: 3.1.6
host.iobroker_prod | 2021-01-14 02:00:49.917 | info | instance system.adapter.backitup.0 started with pid 1048
host.iobroker_prod | 2021-01-14 02:00:19.876 | info | Restart adapter system.adapter.backitup.0 because enabled
host.iobroker_prod | 2021-01-14 02:00:19.875 | info | instance system.adapter.backitup.0 terminated with code 0 (NO_ERROR)
host.iobroker_prod | 2021-01-14 02:00:19.875 | error | Caught by controller[1]: at OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
host.iobroker_prod | 2021-01-14 02:00:19.874 | error | Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
host.iobroker_prod | 2021-01-14 02:00:19.874 | error | Caught by controller[1]: at runMicrotasks (<anonymous>)
host.iobroker_prod | 2021-01-14 02:00:19.874 | error | Caught by controller[1]: at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
host.iobroker_prod | 2021-01-14 02:00:19.874 | error | Caught by controller[1]: Error: Rate Limit Exceeded
host.iobroker_prod | 2021-01-14 02:00:19.861 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejecte
backitup.0 | 2021-01-14 02:00:19.339 | info | (122) Terminated (NO_ERROR): Without reason
backitup.0 | 2021-01-14 02:00:19.338 | info | (122) terminating
backitup.0 | 2021-01-14 02:00:19.320 | info | (122) cleaned everything up...
backitup.0 | 2021-01-14 02:00:19.318 | error | at OAuth2Client.requestAsync (/opt/iobroker/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
backitup.0 | 2021-01-14 02:00:19.318 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
backitup.0 | 2021-01-14 02:00:19.318 | error | at runMicrotasks (<anonymous>)
backitup.0 | 2021-01-14 02:00:19.318 | error | at Gaxios._request (/opt/iobroker/node_modules/gaxios/src/gaxios.ts:140:15)
backitup.0 | 2021-01-14 02:00:19.318 | error | (122) Error: Rate Limit Exceeded
backitup.0 | 2021-01-14 02:00:19.240 | error | (122) unhandled promise rejection: Rate Limit Exceeded
Unhandled | 2021-01-14 02:00:19.230 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

lG Georg

**Comment by simatec** [comment]
In der Google Api scheint da ein Bug zu sein. Wir haben bereits ein Issue aufgemacht. 
Einge User haben allerdings berichtet, dass eine krumme Backupzeit Abhilfe schaffen kann. Eventuell hat Google zuviel gleichzeitige Anfragen Nachts um 2 Uhr. Ändere mal die Zeit auf etwas krummes

**Comment by georg1210** [comment]
Danke, das versuche ich mal. An alle Mitleser: 01:47h CET gehört schon mir ;-)
Generell danke für den Adapter - I like!

**Comment by simatec** [comment]
> An alle Mitleser: 01:47h CET gehört schon mir ;-)

😂

**Comment by georg1210** [comment]
Update: Die ersten zwei Backups zu krummer Backupzeit sind problemlos gelaufen
