### ISSUE TITLE
Backup two Redis instances

### ISSUE THREAD

**Issue by Sineos** [simatec/ioBroker.backitup#738]
**Is your feature request related to a problem? Please describe.**
The iobroker documentation reccomends to use two Redis instances, one for objects and one for states.
I only found the option to backup one Redis instance.

**Describe the solution you'd like**
Option to backup two Redis isntances

**Describe alternatives you've considered**
n/a

**Additional context**
Thanks for this adapter and your commitment. Appreciated.

**Comment by simatec** [comment]
You can back up a second Redis server with another instance of Backitup.

You configure this as slave backup and the first instance as master.
The slave instance can be configured so that it does not consume system load and is only started during the backup process.

Can you please post me the link where the recommendation with two Redis servers is described.

**Comment by Sineos** [comment]
Thanks for coming back to this.



> Can you please post me the link where the recommendation with two Redis servers is described.

https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/config/redis.md#switch-iobroker-database-to-redis --> States and objects in the same or separate Redis processes?

the same in: https://www.iobroker.net/#de/documentation/config/redis.md

> You configure this as slave backup and the first instance as master.
> The slave instance can be configured so that it does not consume system load and is only started during the backup process.

Thanks 👍
