### ISSUE TITLE
Backitup - Grafana - https - self-signed certificate

### ISSUE THREAD

**Issue by RAVENMASTER887** [simatec/ioBroker.backitup#765]
**Describe the bug**  
Backitup kann kein Grafana Backup erstellen, wenn Grafana mittels self-signed Certificate auf https eingestellt ist.

**To Reproduce**  
1. Grafana mittels z.B. https://www.turbogeek.co.uk/grafana-how-to-configure-ssl-https-in-grafana/ auf https umstellen.
2. Backup von Grafana über Backitup vom ioBroker aus, starten.

**Screenshots & Logfiles**
[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is not available: Error: self signed certificate
[DEBUG] [grafana] - Grafana is not available!
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - Grafana Backup cannot created ...
[DEBUG] [grafana] - done

**Versions:**  
 - Adapter version: 2.4.12 und 2.4.16
 - JS-Controller version: 4.0.23 
 - Node version: v12.22.12 
 - Operating system: Raspian 10 (buster)

**Additional context**  
Thread im Forum zu dem Thema: https://forum.iobroker.net/topic/58919/backitup-grafana-https-self-signed-certificate

**Comment by ESDN83** [comment]
Hi, same error for me ....
using a own SSL Root and intermediate to secure Grafana ... 
Same switch as for the CCU Backup has to be implemented in order to trust private certificates!

[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is not available: Error: self signed certificate in certificate chain
[DEBUG] [grafana] - Grafana is not available!
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - Grafana Backup cannot created ...
[DEBUG] [grafana] - done

**Comment by simatec** [comment]
Please test v2.5.4 an check the Settings on Grafana Tab for signed Certificates

![image](https://user-images.githubusercontent.com/39792461/199518220-e4ad691f-38c7-49b2-b231-934208bf8ffd.png)

**Comment by ESDN83** [comment]
Working like a charm now: 👍 

[DEBUG] [grafana] - Start Grafana Backup ...
[DEBUG] [grafana] - Created grafana_tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Created dashboard directory
[DEBUG] [grafana] - Created dashboards_manually_restore directory
[DEBUG] [grafana] - Created datasource directory
[DEBUG] [grafana] - start Grafana request ...
[DEBUG] [grafana] - Grafana is available ... Status: 200
[DEBUG] [grafana] - found Dashboard: photovoltaik
[DEBUG] [grafana] - found Dashboard: wetter-epaper
[DEBUG] [grafana] - found Dashboard: usv
[DEBUG] [grafana] - found Dashboard: wetter
[DEBUG] [grafana] - found Dashboard: heizen
[DEBUG] [grafana] - start Grafana backup compress ...
[DEBUG] [grafana] - Backup created: /opt/iobroker/backups/grafana_2022_11_02-17_56_15_iBroker_Backup_backupiobroker.tar.gz
[DEBUG] [grafana] - Try deleting the Grafana tmp directory: "/opt/iobroker/backups/grafana_tmp"
[DEBUG] [grafana] - Grafana tmp directory "/opt/iobroker/backups/grafana_tmp" successfully deleted
[DEBUG] [grafana] - done

**Comment by simatec** [comment]
Perfect … thx

**Comment by RAVENMASTER887** [comment]
Nach dem Update auf 2.5.4 funktioniert das Backup jetzt auch mit dem selbst erstellten Zertifikat. Perfekt, Danke.
